src/main/java/ua/dnipro/ntudp/varenyk_mykyta/library/model/Order.java
package ua.dnipro.ntudp.varenyk_mykyta.library.model;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.sql.Date;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Objects;

/**
 * Order entity.
 *
 * @author Mykyta Varenyk
 *
 */

public class Order extends Entity {
    private LocalDateTime approvedTime;
    private int accountId;
    private Long librarianId;
    private boolean isApproved;
    private boolean inReadingHall;
    private LocalDate expiredAt;
    private String expired;
    private int daysCount;
    private int hoursCount;
    private int bookId;
    private boolean isReturned;

    public boolean isReturned() {
        return isReturned;
    }

    public void setReturned(int isReturned) {
        if (isReturned == 1){
            this.isReturned = true;
        }else {
            this.isReturned = false;
        }
    }

    public int getBookId() {
        return bookId;
    }

    public void setBookId(int bookId) {
        this.bookId = bookId;
    }

    public int getHoursCount() {
        return hoursCount;
    }

    public void setHoursCount(int hoursCount) {
        this.hoursCount = hoursCount;
    }

    public String getExpired() {
        return expired;
    }

    public void setExpired(String expired) {
        this.expired = expired;
    }

    public int getDaysCount() {
        return daysCount;
    }

    public void setDaysCount(int daysCount) {
        this.daysCount = daysCount;
    }

    public LocalDateTime getApprovedTime() {
        return approvedTime;
    }

    public void setApprovedTime(Date approved_time) {
        if (approved_time != null) {
            this.approvedTime = approved_time.
                    toInstant().
                    atZone(ZoneId.systemDefault()).
                    toLocalDateTime();
        }
    }

    public int getAccountId() {
        return accountId;
    }

    public void setAccountID(int account_id) {
        this.accountId = account_id;
    }

    public Long getLibrarianId() {
        return librarianId;
    }

    public void setLibrarianId(Long librarianId) {
        this.librarianId = librarianId;
    }

    public boolean getIsApproved() {
        return isApproved;
    }

    public void setApproved(int approved) {
        if (approved == 1){
            isApproved = true;
        }
    }

    public boolean getIsInReadingHall() {
        return inReadingHall;
    }

    public void setInReadingHall(int inReadingHall) {
        if (inReadingHall == 1) {
            this.inReadingHall = true;
        }
    }

    public LocalDate getExpiredAt() {
        return expiredAt;
    }

    public void setExpiredAt(Date expiredAt) {
        if (expiredAt != null) {
            this.expiredAt = expiredAt.toInstant().
                    atZone(ZoneId.systemDefault()).
                    toLocalDate();
        }
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Order order = (Order) o;
        return accountId == order.accountId &&
                isApproved == order.isApproved &&
                inReadingHall == order.inReadingHall &&
                daysCount == order.daysCount &&
                hoursCount == order.hoursCount &&
                bookId == order.bookId &&
                Objects.equals(approvedTime, order.approvedTime) &&
                Objects.equals(librarianId, order.librarianId) &&
                Objects.equals(expiredAt, order.expiredAt) &&
                Objects.equals(expired, order.expired);
    }

    @Override
    public int hashCode() {
        return Objects.hash(approvedTime, accountId, librarianId, isApproved, inReadingHall, expiredAt, expired, daysCount, hoursCount, bookId);
    }

    @Override
    public String toString() {
        return "Order{" +
                "approved_time=" + approvedTime +
                ", account_id=" + accountId +
                ", librarianId=" + librarianId +
                ", isApproved=" + isApproved +
                ", inReadingHall=" + inReadingHall +
                ", expiredAt=" + expiredAt +
                '}';
    }
}

src/main/java/ua/dnipro/ntudp/varenyk_mykyta/library/model/User.java
package ua.dnipro.ntudp.varenyk_mykyta.library.model;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 * User entity.
 *
 * @author Mykyta Varenyk
 *
 */

public class User extends Entity {
    private String login;

    private String email;

    private String password;

    private int roleId;

    private String firstName;

    private String lastName;

    private String firstNameUa;

    private String lastNameUa;

    private String role;

    private boolean isBlocked;

    private boolean hasOrders;

    public String getFirstNameUa() {
        return firstNameUa;
    }

    public void setFirstNameUa(String firstNameUa) {
        this.firstNameUa = firstNameUa;
    }

    public String getLastNameUa() {
        return lastNameUa;
    }

    public void setLastNameUa(String lastNameUa) {
        this.lastNameUa = lastNameUa;
    }

    public void setBlocked(boolean blocked) {
        isBlocked = blocked;
    }

    public boolean getHasOrders() {
        return hasOrders;
    }

    public void setHasOrders(int hasOrders) {
        if (hasOrders == 1){
            this.hasOrders = true;
        }else {
            this.hasOrders = false;
        }
    }

    public boolean isBlocked() {
        return isBlocked;
    }

    public void setBlocked(int blocked) {
        if (blocked == 1)
            isBlocked = true;
        else
            isBlocked = false;

    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getRoleId() {
        return roleId;
    }

    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Override
    public String toString() {
        return "User{" +
                "login='" + login + '\'' +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                ", roleId=" + roleId +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", firstNameUa='" + firstNameUa + '\'' +
                ", lastNameUa='" + lastNameUa + '\'' +
                ", role='" + role + '\'' +
                ", isBlocked=" + isBlocked +
                ", hasOrders=" + hasOrders +
                '}';
    }
}

src/main/java/ua/dnipro/ntudp/varenyk_mykyta/library/web/OrderController.java
package ua.dnipro.ntudp.varenyk_mykyta.library.web;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;
import ua.dnipro.ntudp.varenyk_mykyta.library.db.bean.UserOrderBean;
import ua.dnipro.ntudp.varenyk_mykyta.library.model.User;
import ua.dnipro.ntudp.varenyk_mykyta.library.util.Util;
import ua.dnipro.ntudp.varenyk_mykyta.library.web.services.OrderService;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.util.List;

@Controller
public class OrderController {
    private static Logger LOGGER = LogManager.getLogger(OrderController.class);

    @Autowired
    private OrderService orderService;

    @GetMapping(value = "*/user/orders")
    @ResponseBody
    public ModelAndView userOrders(HttpServletRequest req){
        LOGGER.debug("OrdersController#userOrders started");

        HttpSession session = req.getSession();

        String languageCode = Util.getLanguageCodeFromSession(session);

        int currentPage = 1;

        int recordsPerPage = 2;

        if (req.getParameter("page") != null){
            currentPage = Integer.parseInt(req.getParameter("page"));
        }

        LOGGER.debug("currentPage -> {}",currentPage);

        User user = (User) session.getAttribute("user");

        int id = user.getId();

        LOGGER.debug("user id -> {}",id);

        List<UserOrderBean> userOrderBeans = orderService.getUserOrderBeansWithPagination(currentPage,recordsPerPage,languageCode, id);

        LOGGER.debug("userOrderBeans with limit:{} and offset:{} -> {}",currentPage,recordsPerPage,userOrderBeans);

        ModelAndView modelAndView = new ModelAndView("user/orders");

        modelAndView.addObject("userOrderBeans",userOrderBeans);

        modelAndView.addObject("currentPage",currentPage);

        modelAndView.addObject("recordsPerPage",recordsPerPage);

        modelAndView.addObject("numOfPages",orderService.countOrdersByUserId(id,recordsPerPage));

        return modelAndView;
    }


}

src/main/java/ua/dnipro/ntudp/varenyk_mykyta/library/web/UserController.java
package ua.dnipro.ntudp.varenyk_mykyta.library.web;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;
import ua.dnipro.ntudp.varenyk_mykyta.library.Path;
import ua.dnipro.ntudp.varenyk_mykyta.library.db.dao.Fields;
import ua.dnipro.ntudp.varenyk_mykyta.library.model.User;
import ua.dnipro.ntudp.varenyk_mykyta.library.util.Util;
import ua.dnipro.ntudp.varenyk_mykyta.library.web.services.ServiceUtil;
import ua.dnipro.ntudp.varenyk_mykyta.library.web.services.UserService;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.util.List;

@Controller
public class UserController {
    private static Logger LOGGER = LogManager.getLogger(UserController.class);

    @Autowired
    private UserService userService;

    @PostMapping(value = "*/login")
    @ResponseBody
   public ModelAndView login(HttpServletRequest req){
        LOGGER.debug("UsersController#login started");

        ModelAndView modelAndView;

        HttpSession session = req.getSession();

        String login = req.getParameter(Fields.USER_LOGIN);

        String password = req.getParameter(Fields.USER_PASSWORD);

        String errorMessage;

        String languageCode = Util.getLanguageCodeFromSession(session);

        modelAndView = new ModelAndView(Path.PAGE_ERROR_PAGE);

        if (login == null || password == null || login.isEmpty() || password.isEmpty()) {
           errorMessage = "Login/password cannot be empty";
           LOGGER.error("errorMessage -> {}",errorMessage);
           modelAndView.addObject("errorMessage",errorMessage);
           return modelAndView;
        }
       return userService.validateLoginInformation(login,password,languageCode,session);
   }

     @GetMapping(value = "*/user/home")
     public ModelAndView userHomePage(){
       return new ModelAndView(Path.PAGE_USER_HOME_PAGE);
   }

      @GetMapping(value = "*/admin/home")
      public ModelAndView adminHomePage(){
       return new ModelAndView(Path.PAGE_ADMIN_HOME_PAGE);
   }

     @GetMapping(value = "*/librarian/home")
      public ModelAndView librarianHomePage(){
       return new ModelAndView(Path.PAGE_LIBRARIAN_HOME_PAGE);
   }

     @PostMapping(value = "*/logout")
     public ModelAndView logout(HttpServletRequest req){
         HttpSession session = req.getSession(false);

         if (session != null) {
            session.invalidate();
            LOGGER.debug("Session invalidated");
        }else{
            LOGGER.debug("there is no active session");
        }
        return new ModelAndView(Path.PAGE_INDEX_REDIRECT);
    }

    @GetMapping(value = "*/admin/users")
    @ResponseBody
    public ModelAndView adminUsersPage(HttpServletRequest req,ModelAndView modelAndView){
        modelAndView = new ModelAndView(Path.PAGE_ADMIN_USERS_PAGE);

        int currentPage = 1;

        int recordsPerPage = 2;

        if (req.getParameter("page") != null){
            currentPage = Integer.parseInt(req.getParameter("page"));
        }

        LOGGER.debug("page -> {}",currentPage);

        List<User> users = userService.getUsersWithPagination(currentPage,recordsPerPage);

        LOGGER.debug("users with limit:{} and offset:{} -> {}",currentPage,recordsPerPage,users);

        modelAndView.addObject("users",users);

        modelAndView.addObject("currentPage",currentPage);

        modelAndView.addObject("recordsPerPage",recordsPerPage);

        modelAndView.addObject("numOfPages", ServiceUtil.getNumberOfPages(userService.countUsers(),recordsPerPage));

        return modelAndView;
    }
}

src/main/webapp/jsp/user/home_page.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="h" tagdir="/WEB-INF/tags" %>
<c:set var="language" value="${not empty param.language ? param.language : not empty language ? language : 'en'}" scope="session" />

<fmt:setBundle basename="text"/>


<html>
<head>
    <title>User home page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
          crossorigin="anonymous">
    <link rel="stylesheet" href="../../css/index.css">
</head>
<body>
<div class="wrapper">
<%@include file="/WEB-INF/jspf/header.jspf"%>
<main>
    <br/><br/><br/>
    <div class="wrapper">
        <h1> <fmt:message key="label.userGreeting"/>, ${sessionScope.user.login}!</h1>
        <div class="container">
            <div class="row">
                <div class="user-item">
                    <div class="row">
                        <div class="col s9">
                            <div class="row">
                                <div class="col s3">
                                    <fmt:message key="label.email"/>
                                    <span>${sessionScope.user.email}</span>
                                </div>
                            </div><br/>
                            <div class="row">
                                <div class="col s3">
                                    <fmt:message key="label.login"/>
                                    <span>${sessionScope.user.login}</span>
                                </div>
                            </div><br/>
                            <div class="row">
                                <div class="col s3">
                                    <fmt:message key="label.firstName"/>
                                    <span>${sessionScope.user.firstName}</span>
                                </div>
                            </div><br/>
                            <div class="row">
                                <div class="col s3">
                                    <fmt:message key="label.lastName"/>
                                    <span>${sessionScope.user.lastName}</span>
                                </div>
                            </div><br/>
                        </div>
                    </div><br/>
                </div>
            </div>
        </div>
        <h:change-language path="redirect:/FinalProject/controller/user/home"/>
        <%@include file="/WEB-INF/jspf/footer.jspf"%>
    </div>
    </main>
</div>
</body>
</html>

src/main/webapp/jsp/user/make_order_in_reading_hall.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
<jsp:text>Make order: </jsp:text>
<div class="col s4">
    <div class="show-create-form">
        <form action="${pageContext.request.contextPath}/controller/user/confirm-in-reading-hall-order" method="post">
            <input type="number" hidden name="id" value="${requestScope.id}">

            <label for="hours_count">hours amount: </label>
            <input id="hours_count" type="number" min="1" max="4" required
                   placeholder="1-4" name="hours_count">
            <br>
            <input type="submit" class="btn" value="confirm"/>
        </form>
    </div>
</div>
</div>
</body>
</html>

src/main/webapp/jsp/user/make_order_take_home.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
<jsp:text>Make order: </jsp:text>
<div class="col s4">
    <div class="show-create-form">
        <form action="${pageContext.request.contextPath}/controller/user/confirm-take-home-order" method="post">
            <input type="number" hidden name="id" value="${requestScope.id}">

            <label for="days_count">days amount: </label>
            <input id="days_count" type="number" min="1" max="1500" required
                   placeholder="0-1500" name="days_count">
            <br>
            <input type="submit" class="btn" value="confirm"/>
        </form>
    </div>
</div>
</div>
</body>
</html>

src/main/webapp/jsp/user/orders.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" language="java" %>
<%@taglib prefix="f" uri="http://library.varenyk_mykyta.ntudp.dnipro.ua/functions" %>
<%@taglib prefix="h" tagdir="/WEB-INF/tags" %>
<c:set var="language" value="${not empty param.language ? param.language : not empty language ? language : 'en'}" scope="session" />

<fmt:setBundle basename="text"/>

<html>
<head>
    <title>User/Orders</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
          crossorigin="anonymous">
    <link rel="stylesheet" href="/css/index.css">
</head>
<div class="wrapper">
<%@include file="/WEB-INF/jspf/header.jspf"%>
<main>
    <div class="page-wrapper wrapper">
        <div class="container">
            <div class="row">
                <c:forEach var="bean" items="${requestScope.userOrderBeans}">
                <c:if test="${bean.approvedTime != null}">
                    <div class="order-item">
                        <div class="row">
                            <div class="col s9">
                                <div class="row">
                                    <div class="col s3">
                                        ID:
                                        <span>${bean.orderId}</span>
                                    </div>
                                </div>
                                    <div class="row">
                                            <div class="col s3">
                                                <fmt:message key="label.name"/>
                                                <span>${bean.name}</span>
                                            </div>
                                    </div>

                                <div class="row">
                                    <div class="col s3">
                                        <fmt:message key="label.publisher"/>
                                        <span>${bean.publisher}</span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col s3">
                                        <fmt:message key="label.author"/>
                                        <span>${bean.author}</span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col s3">
                                        <fmt:message key="orders_jsp.approvedByLibrarian"/>
                                        <span>${bean.librarianId}</span>
                                    </div>
                                </div>
                                <div class="row">
                                    <c:choose>
                                        <c:when test="${bean.returned == true}">
                                            <span>returned</span>
                                        </c:when>
                                        <c:when test="${bean.daysCount != 0}">
                                            <c:set var="delay" value="${f:delay(bean.approvedTime)}"/>
                                            <div class="col s3">
                                                <c:choose>
                                                    <c:when test="${delay >= bean.daysCount}">
                                                        <fmt:message key="label.penaltySize"/>
                                                        <span>${10 * (delay - bean.daysCount)}</span>
                                                    </c:when>
                                                    <c:otherwise>
                                                        <fmt:message key="label.daysCount"/>
                                                        <span>${bean.daysCount - delay}</span>
                                                    </c:otherwise>
                                                </c:choose>
                                            </div>
                                        </c:when>
                                        <c:otherwise>
                                            <c:set var="delay" value="${f:delayHours(bean.approvedTime)}"/>
                                            <div class="col s3">
                                                <c:choose>
                                                    <c:when test="${delay > bean.hoursCount}">
                                                        <fmt:message key="label.penaltySize"/>
                                                        <span>${3*(delay - bean.hoursCount)}</span>
                                                    </c:when>
                                                    <c:otherwise>
                                                        <fmt:message key="label.hoursCount"/>
                                                        <span>${bean.hoursCount - delay}</span>
                                                    </c:otherwise>
                                                </c:choose>
                                            </div>
                                        </c:otherwise>
                                    </c:choose>
                                </div>
                                <div class="row">
                                    <div class="col s3">
                                        <form method="post"
                                              action="${pageContext.request.contextPath}/controller/user/return-book">
                                            <input type="number" hidden name="id" value="${bean.orderId}">
                                            <input type="submit" class="btn" value="return">
                                        </form><br/>
                                    </div>
                                </div>
                            </div>
                            </div>
                    </div>
                    </div><br/>
            </c:if>
                </c:forEach>
            <ul class="pagination">
                <c:if test="${requestScope.currentPage != 1}">
                    <li class="disabled">
                        <a class="page-link previous" href="${pageContext.request.contextPath}/controller/user/orders?page=${requestScope.currentPage-1}">                                        Previous
                        </a>
                    </li>
                </c:if>

                <c:forEach begin="1" end="${requestScope.numOfPages}" varStatus="i">
                    <c:choose>
                        <c:when test="${requestScope.currentPage eq i.index}}">
                            <li class="page-active">
                                <a class="page-link">
                                        ${i.index}<span class="sr-only">(current)</span>
                                </a>
                            </li>
                        </c:when>
                        <c:otherwise>
                            <li class="page-active">
                                <a class="page-link" href="orders?page=${i.index}">${i.index}</a>
                            </li>
                        </c:otherwise>
                    </c:choose>
                </c:forEach>

                <c:if test="${requestScope.currentPage lt requestScope.numOfPages}">
                    <li class="page-item">
                        <a class="page-link" href="${pageContext.request.contextPath}/controller/user/orders?page=${requestScope.currentPage+1}">Next</a>
                    </li>
                </c:if>
            </ul>
            <h:change-language path="redirect:/FinalProject/controller/user/orders"/>
            <%@include file="/WEB-INF/jspf/footer.jspf"%>
            </div>
        </div><br/>
</main>
</div>

</body>
</html>